// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PrPxI2IfoceT2jjYrY8Lt3vOOg0jw3A',
    appId: '1:863289356590:web:f68e0350063fe2aebf8abf',
    messagingSenderId: '863289356590',
    projectId: 'swapla-deneme-1',
    authDomain: 'swapla-deneme-1.firebaseapp.com',
    storageBucket: 'swapla-deneme-1.appspot.com',
    measurementId: 'G-9NJZDGL0X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0Ard2STuel18lCGguZfRwSvkuN0mxKE',
    appId: '1:863289356590:android:bd5a2168747f9ff8bf8abf',
    messagingSenderId: '863289356590',
    projectId: 'swapla-deneme-1',
    storageBucket: 'swapla-deneme-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9Le8Sv49dRt_gVqEEfkRw1DgAP4Mv-0',
    appId: '1:863289356590:ios:71ba23e8d88cffb3bf8abf',
    messagingSenderId: '863289356590',
    projectId: 'swapla-deneme-1',
    storageBucket: 'swapla-deneme-1.appspot.com',
    androidClientId: '863289356590-1epbtpe84ointbdd2mumjci0ejhrr8fq.apps.googleusercontent.com',
    iosClientId: '863289356590-mm25oma6r0onoho2pi4erbgeo6qq2er7.apps.googleusercontent.com',
    iosBundleId: 'fatih.n.turkel.swapla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW9Le8Sv49dRt_gVqEEfkRw1DgAP4Mv-0',
    appId: '1:863289356590:ios:5ec75459b4db42d8bf8abf',
    messagingSenderId: '863289356590',
    projectId: 'swapla-deneme-1',
    storageBucket: 'swapla-deneme-1.appspot.com',
    androidClientId: '863289356590-1epbtpe84ointbdd2mumjci0ejhrr8fq.apps.googleusercontent.com',
    iosClientId: '863289356590-oo36m8adg2qe07q57jd4f9et2aie2nij.apps.googleusercontent.com',
    iosBundleId: 'com.example.takasla',
  );
}
